### ISSUE TITLE
include_docs seems not work

### ISSUE THREAD

**Issue by copyhold** [pouchdb/pouchdb-list#1]
using a list function with include_docs=true will return the document in
row.doc after row=getRow()
Which does not work in this plugin.
It also not set a row.value

**Comment by marten-de-vries** [comment]
Thanks for reporting. Does `db.list("list/name/stuff", {query: {include_docs: true}})` fix your problem?

**Comment by copyhold** [comment]
Yes, it helps. Thank you
It is not the same as on pouchdb itself - include_docs is within 'query'

**Comment by marten-de-vries** [comment]
Glad that solved the issue. You're right it's different, but it's for a good reason: pouchdb-list has a lot more configuration properties you can set. Pretty much the whole `req` object that's passed into your list function is configurable (with sensible defaults given). If you would call a list function using a browser, the `include_docs` option would be in the query part of the url (?include_docs=true&etc). It's also under req.query in the design doc IIRC. So that's why it's there.
